# Generated by Django 5.1.7 on 2025-03-07 16:23

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the patient', primary_key=True, serialize=False)),
                ('medical_record_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Medical record number or other external identifier', null=True, unique=True)),
                ('date_of_birth', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text="Patient's date of birth", null=True)),
                ('email', encrypted_model_fields.fields.EncryptedEmailField(help_text='Primary email for communications')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the email has been verified')),
                ('phone_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Primary phone number for communications', null=True)),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether the phone number has been verified')),
                ('preferred_contact_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('CALL', 'Phone Call'), ('NONE', 'No Communication')], default='EMAIL', help_text="Patient's preferred method of contact", max_length=10)),
                ('contact_time_preferences', models.JSONField(default=dict, help_text='JSON containing preferred contact times')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this patient record is active')),
                ('scheduled_deletion_date', models.DateField(blank=True, help_text='Date when this record should be automatically deleted', null=True)),
                ('anonymized', models.BooleanField(default=False, help_text='Whether this record has been anonymized')),
                ('has_active_consent', models.BooleanField(default=False, help_text='Whether this patient has provided active consent for data processing')),
                ('verification_token', models.CharField(blank=True, help_text='Token used for email/phone verification or password reset', max_length=64, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, help_text='Expiration time for the verification token', null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, help_text='When the patient was last contacted', null=True)),
                ('contact_attempts', models.PositiveIntegerField(default=0, help_text='Number of contact attempts made')),
                ('successful_contacts', models.PositiveIntegerField(default=0, help_text='Number of successful contacts')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User account for this patient', on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'permissions': [('view_sensitive_data', 'Can view sensitive patient data'), ('export_patient_data', 'Can export patient data'), ('anonymize_patient', 'Can anonymize patient data'), ('contact_patient', 'Can contact patient directly')],
                'indexes': [models.Index(fields=['is_active'], name='patients_pa_is_acti_54ba9f_idx'), models.Index(fields=['has_active_consent'], name='patients_pa_has_act_3dedc4_idx'), models.Index(fields=['email_verified'], name='patients_pa_email_v_aeb8a2_idx'), models.Index(fields=['phone_verified'], name='patients_pa_phone_v_580e95_idx'), models.Index(fields=['last_contacted_at'], name='patients_pa_last_co_f0a2b6_idx')],
            },
        ),
    ]
