# Generated by Django 5.1.7 on 2025-03-08 16:29

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_group',
            field=models.CharField(blank=True, choices=[('0-18', '0-18'), ('19-35', '19-35'), ('36-50', '36-50'), ('51-65', '51-65'), ('65+', '65+')], help_text='Age group for demographic segmentation', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], help_text="Patient's gender for demographic segmentation", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='language_preference',
            field=models.CharField(blank=True, default='en', help_text='Preferred language for communications', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='General location for geographic targeting', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Postal code for geographic segmentation', null=True),
        ),
    ]
