# Generated by Django 4.2.9 on 2025-03-11 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When the patient record was anonymized', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_time_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='JSON containing preferred contact times', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
