# Generated by Django 4.2.9 on 2025-03-13 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_patient_anonymized_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('GENERAL', 'General Data Processing'), ('MARKETING', 'Marketing Communications'), ('RESEARCH', 'Research Usage'), ('THIRD_PARTY', 'Third Party Sharing'), ('SENSITIVE_DATA', 'Process Sensitive Data'), ('AUTOMATED_DECISION', 'Automated Decision Making')], max_length=20)),
                ('granted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document_version', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'indexes': [models.Index(fields=['patient', 'consent_type'], name='patients_co_patient_a44c1b_idx'), models.Index(fields=['timestamp'], name='patients_co_timesta_31b72b_idx')],
            },
        ),
    ]
