# Generated by Django 4.2.9 on 2025-03-08 18:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_age_group_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(blank=True, help_text="Patient's date of birth", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(help_text='Primary email for communications', max_length=50, unique=True)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('fr', 'French'), ('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian')], default='fr', help_text='Preferred language for communications', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.CharField(blank=True, help_text='General location for geographic targeting', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(blank=True, help_text='Medical record number or other external identifier', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Primary phone number for communications', max_length=20, null=True)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code for geographic segmentation', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='preferred_contact_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('CALL', 'Phone Call'), ('NONE', 'No Communication')], default='NONE', help_text="Patient's preferred method of contact", max_length=10),
        ),
    ]
