# Generated by Django 4.2.9 on 2025-03-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '__first__'),
        ('patients', '0003_alter_patient_date_of_birth_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='campaign_preferences',
            field=models.JSONField(default=dict, help_text='Patient preferences for different campaign types'),
        ),
        migrations.AddField(
            model_name='patient',
            name='engagement_score',
            field=models.FloatField(default=0.0, help_text="Patient's engagement score based on communication history"),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_campaign_response',
            field=models.DateTimeField(blank=True, help_text='When the patient last responded to a campaign', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='patients', to='campaign.patientsegment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(help_text='Primary email for communications', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone number for communications', max_length=20, null=True),
        ),
    ]
