# Generated by Django 5.1.6 on 2025-04-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_consentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='consent_method',
            field=models.CharField(choices=[('WEB_FORM', 'Web Form'), ('API', 'API Request'), ('STAFF', 'Staff Member'), ('IMPORT', 'Data Import')], default='WEB_FORM', help_text='How the consent was collected', max_length=20),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/device information', null=True),
        ),
    ]
