# Generated by Django 5.1.6 on 2025-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_communicationlog_responded_at'),
        ('patients', '0004_consentrecord_consent_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='campaign_preferences',
        ),
        migrations.AddField(
            model_name='patient',
            name='campaign_preferences',
            field=models.ManyToManyField(blank=True, default=dict, help_text='Patient preferences for different campaign types', related_name='patient', to='campaigns.campaign'),
        ),
    ]
