# Generated by Django 5.1.6 on 2025-05-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_remove_patient_campaign_preferences_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="preferred_contact_methods",
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_contact_methods",
            field=models.JSONField(
                default=list, help_text="List of patient's preferred methods of contact"
            ),
        ),
    ]
