# Generated by Django 4.2.9 on 2025-03-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_age_groups', models.JSONField(default=list)),
                ('target_locations', models.JSONField(default=list)),
                ('target_languages', models.JSONField(default=list)),
                ('email_template', models.TextField(blank=True)),
                ('sms_template', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campaign Category',
                'verbose_name_plural': 'Campaign Categories',
            },
        ),
        migrations.CreateModel(
            name='PatientSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(help_text='Segmentation criteria in JSON format')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='segments', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Patient Segment',
                'verbose_name_plural': 'Patient Segments',
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('CALL', 'Phone Call'), ('NONE', 'No Communication')], help_text='Type of communication channel used', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('RESPONDED', 'Responded')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(null=True)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if communication failed')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata about the communication')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
