# Generated by Django 4.2.9 on 2025-03-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaigncategory'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['status'], name='campaigns_c_status_87f39c_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['sent_at'], name='campaigns_c_sent_at_27bf46_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['campaign', 'patient'], name='campaigns_c_campaig_0d786d_idx'),
        ),
    ]
