# Generated by Django 4.2.9 on 2025-03-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(default='OTHER', on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaigncategory'),
        ),
        migrations.AlterField(
            model_name='campaigncategory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
