# Generated by Django 5.1.6 on 2025-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_created_by_campaign_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='responded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
